version: '3'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.32
    environment:
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_DATABASE: inventorymanagement
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./inventorymanagement.sql:/docker-entrypoint-initdb.d/inventorymanagement.sql
    networks:
      - springboot-mysql-net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysqldb
      PMA_USER: db_user
      PMA_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: root
    networks:
      - springboot-mysql-net

  inventory-management-webservices:
    container_name: inventory-management-webservices
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/inventorymanagement?useSSL=false&allowPublicKeyRetrieval=true
      - spring.datasource.username=db_user
      - spring.datasource.password=db_password
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.jpa.show-sql=true
    networks:
      - springboot-mysql-net
    restart: on-failure

networks:
  springboot-mysql-net:
